allow_network: false
firerunner_path: "firerunner"
kernel_path: "vmlinux-4.20.0"
runtimefs_dir: "./"
appfs_dir: "output/"
functions:
  gh_repo:
    vcpus: 1
    memory: 128
    runtimefs: "python3.ext4"
    appfs: "gh_repo.img"
    concurrency_limit: 100
  go_grader:
    vcpus: 1
    memory: 256
    runtimefs: "python3.ext4"
    appfs: "go_grader.img"
    concurrency_limit: 100
  grades:
    vcpus: 1
    memory: 128
    runtimefs: "python3.ext4"
    appfs: "grades.img"
    concurrency_limit: 100
  generate_report:
    vcpus: 1
    memory: 128
    runtimefs: "python3.ext4"
    appfs: "generate_report.img"
    concurrency_limit: 100

